### ISSUE TITLE
How to use Forge 1.12.2 

### ISSUE THREAD

**Issue by loprima-l** [luuxis/minecraft-java-core#14]
I tried to use your library with Forge 1.12.2 but i can't figure out where do i need to put my forge file

Thanks

**Comment by luuxis** [comment]
hello, you can use the code here for forge, fabric, quilt.

https://github.com/luuxis/minecraft-java-core/blob/dev/test/index.js

**Comment by loprima-l** [comment]
thanks

**Comment by loprima-l** [comment]
Hi, im using those options, but since I updated the package it doesn't work anymore. If I'm tying with another version, it work.

```javascript
let opt = {
        url: 'https://api.the-lost-site.fr/mc-files/list/v3/',
        authenticator: await Mojang.login(username),
        timeout: 10000,
        path: app.getPath('userData') + "/clients/v3",
        version: '1.12.2',
        detached: false,
        downloadFileMultiple: 10,

        loader: {
            type: 'forge',
            build: '14.23.5.2854',
            enable: true
        },

        verify: true,
        ignored: ['loader', 'options.txt'],

        java: true,

        memory: {
            min: '2G',
            max: '4G'
        }
    }
```

Error :

```
(node:1562) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'version')
    at java.GetJsonJava (/Users/loprima/Documents/client/node_modules/minecraft-java-core/build/Minecraft/Minecraft-Java.js:32:95)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Launch.DownloadGame (/Users/loprima/Documents/client/node_modules/minecraft-java-core/build/Launch.js:106:64)
    at async Launch.start (/Users/loprima/Documents/client/node_modules/minecraft-java-core/build/Launch.js:69:20)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:1562) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by loprima-l** [comment]
I've updated it today only, maybe the problem is coming from another thing

**Comment by loprima-l** [comment]
I think it's coming from the way you get versions as older package throws the same error.
I'll get a look at it tomorrow if I've got the time, please let me know if you have any advice.

**Comment by loprima-l** [comment]
Okay, i've found how to fix this issue, it was because of my M1 chip, minecraft doesn't provide any version for this platform in 1.12.2
